### ISSUE TITLE
OpenStorm Could not Compile

### ISSUE THREAD

**Issue by Origincookie122** [JordanSchlick/OpenStorm#6]
I'm using unreal engine 5.2 and get the following when trying to open using ue5.2

![image](https://github.com/JordanSchlick/OpenStorm/assets/83477409/8f30cd49-1dd2-4919-a3d2-4b4f1ab2c618)

Did yes and the rebuild keeps failing to compile.
I then tried with ue5.1, 5.0.3, 4.27

None work
It wants me to recompile from source
Which after setting up the Development environment I noticed you have no openstorm.csproj or openstorm.config file to get external dependences with.
I can link my log files if needed. 

![image](https://github.com/JordanSchlick/OpenStorm/assets/83477409/ca0238d5-90bd-4ef9-b650-b45dc70d8e9c)

**Comment by JordanSchlick** [comment]
I recently fixed some problems today with building for 5.2 
Try rebuilding with 5.2
If that does not work try right clicking on the uproject file and hitting generate visual studio project files and then doing a build in visual studio.
If you can't get visual studio to run for it, you can get the log from Saved/Logs/OpenStorm.log
Send me any errors it generates when trying to build.

**Comment by Origincookie122** [comment]
Ok will do trying now

**Comment by Origincookie122** [comment]
Ok so what I did if anyone else needs to know

1. I tried first opening it to see if it worked again.
2. Since it did not work I then generated the visual studio project files and opened with visual studio
3. it downloaded about 9GB of dev dependences.
4. I built OpenStorm not UE5 the openstorm option
5. ReOpened it and the editor opened
